version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playlistAI
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_HOST: '%' 

  be:
    container_name: be
    build: ./be
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  


  fe-vite:
    container_name: fe-vite
    ports:
      - 8080:8080
    build:
      context: ./vite-fe
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./vite-fe:/app
      - /app/node_modules   