# Generated by Django 3.2.16 on 2023-01-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
