name: Docker Series Build

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: docker build be
      run: docker build ./be  -t andreaspinazzola/music-ai/be:1.0.0
      
    - name: docker build fe
      run: docker build ./be -t andreaspinazzola/music-ai/fe:1.0.0
      
    - name: docker push
      run: |
        docker push andreaspinazzola/music-ai/be:1.0.0
        docker push andreaspinazzola/music-ai/fe:1.0.0
      
